apiVersion: batch/v1
kind: CronJob
metadata:
  name: helm-upgrade-cronjob
spec:
  schedule: "*/50 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: helm-upgrade-container
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - helm upgrade helmsql-release https://github.com/Eklegend/eksqlhelm.git/charts/eksqlchart --values values.yaml
          restartPolicy: OnFailure