# apiVersion: batch/v1
# kind: CronJob
# metadata:
#   name: helm-upgrade-cronjob
# spec:
#   schedule: "*/1 * * * *"
#   jobTemplate:
#     spec:
#       template:
#         spec:
#           containers:
#           - name: helm-upgrade-container
#             image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
#             imagePullPolicy: IfNotPresent
#             command:
#             - /bin/sh
#             - -c
#             - echo "Hello World"
#           restartPolicy: OnFailure