apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume-pvc
#   namespace : {{ .Release.Namespace }}
spec:
    accessModes:
        - {{ .Values.persistentVolume.accessMode }}
    storageClassName: {{ .Values.persistentVolume.storageClassName}}
    resources:
        requests:
            storage: {{ .Values.persistentVolume.size }}
