# templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: secrets-sql
  # namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DB_USER: "{{ .Values.secrets.dbUser }}"
  DB_PASS: "{{ .Values.secrets.dbPass }}"
